name: 'Sanity Runtime Deploy'
description: 'Deploy Sanity blueprints using the @sanity/runtime-cli'
branding:
  icon: 'upload-cloud'
  color: 'red'

inputs:
  # This can be set as an ENV variable or passed directly
  sanity_token:
    description: 'Sanity API token with deploy permissions'
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'
